import { I18n } from "i18n-js";

export const strings = {
  en: {
    myCart: "My Cart",
    orderPlaceSuccess: "Order placed successfully!",
    name: "Name",
    price: "Price",
    addToCart: "Add to Cart",
    credits: "AED",
    starshipClass: "Class",
    goToCart: "Go to Cart",
    quan: "Quan",
    failedToFetch: "Failed to fetch starships",
    homeIcon: "home",
    searchIcon: "search",
    cartIcon: "cart",
    homeIconOutline: "home-outline",
    searchIconOutline: "search-outline",
    cartIconOutline: "cart-outline",
    cod: "COD (Cash on delivery)",
    creditCard: "Credit Card",
    _creditCard: "creditcard",
    totalQuantity: "Total Quantity",
    subTotal: "Subtotal",
    tax: "Tax",
    total: "Total",
    deliveryCharges: "Delivery Charges",
    free: "Free",
    orderSummary: "Order Summary",
    placeOrder: "Place Order",
    selectPayment: "Select Payment Method",
    availableStarShip: "All Starships",
    searchForSarShips: "Search for Starships",
    searchStarShip: "Search Starships",
    emptyCartIcon: "cart-remove",
    noSearchIcon: "search-off",
    notFound: "No results found",
    cartIsEmpty: "Cart is empty",
    home: "Home",
    cart: "Cart",
    search: "Search",
    maximumQuantity: "You have reached the maximum purchase quantity.",
  },
};

export default new I18n(strings);
